                            <?php if($this->isAllowedRoute($this->_instance->getRouteList()->routes['Dashboard'], $this->user )):?>
                            <li class="dropdown">
                                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <strong class="caret"></strong></a>
                                <ul class="dropdown-menu">
                                    <?php echo $this->getPartial('Menus\backup', 'Auth');?>
                                    <?php echo $this->getPartial('Menus\configs', 'Auth');?>
                                    <?php echo $this->getPartial('Menus\library', 'Auth');?>
                                    <?php if($this->isAllowedRoute($this->_instance->getRouteList()->routes['Modules'], $this->user )):?>
                                    <li <?=($this->location == 'Modules') ? 'class="active"':'';?>>
                                        <a href="\Modules">Modules</a>
                                    </li>
                                    <?php endif;?>                    
                                    <?php if($this->isAllowedRoute($this->_instance->getRouteList()->routes['Resources'], $this->user )):?>
                                    <li <?=($this->location == 'Resources') ? 'class="active"':'';?>>
                                        <a href="\Resources">Resources</a>
                                    </li>
                                    <?php endif;?>
                                </ul>
                            </li>
                            <?php endif;?>