<!DOCTYPE >
<html lang="En">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Michael A. Dennis<michaeladennis@comcast.net>">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap-theme.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
            <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
            <!--[if lt IE 9]>
            <script src="/js/html5shiv.js"></script>
            <![endif]-->
        <script type="text/javascript" src="/js/jquery.js"></script>
        
        <script type="text/javascript" src="/js/bootstrap.js"></script>
        <script>
            var userData = <?/*=json_encode($this->test);*/?>;
        </script>
        <script type="text/javascript" src="/js/scripts.js"></script>
        <script>
            $(function()
              {
                /*loadPage(page,limit);*/
                });
        </script>

    </head>
    <body>
    <?php echo $this->getPartial('mainMenu', 'Primary', array('location'=>'Dashboard'));?>
     <h1>Admin Dashboard</h1>
     <p>Create the admin dashboard here.</p>    
    </body>
</html>