<strong>Log Location</strong> : <?=$this->configs->Production->Log->Location;?>
<br/>
<strong>Display Settings</strong><br/>
<strong>Debug System</strong> : <?=$this->configs->Production->Display->Debug;?><br/>
<strong>Display Errors</strong> : <?=$this->configs->Production->Display->Errors;?><br/>
<strong>Display Exceptions</strong> : <?=$this->configs->Production->Display->Exceptions;?><br/>
<br/>

<?php foreach($this->configs->Database as $connectionName  => $connectionData ):?>
<strong>Connection</strong> : <?=$connectionName;?><br/>
<strong>Driver</strong> : <?=$connectionData->driver;?><br/>
<strong>Host</strong> : <?=$connectionData->host;?><br/>
<strong>Schema</strong> : <?=$connectionData->schema;?><br/>
<strong>Username</strong> : <?=$connectionData->username;?><br/>
<strong>Password</strong> : <?=$connectionData->password;?><br/>
<br/>
<?php endforeach;?>