<!DOCTYPE >
<html lang="En">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Michael A. Dennis<michaeladennis@comcast.net>">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap-theme.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
            <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
            <!--[if lt IE 9]>
            <script src="/js/html5shiv.js"></script>
            <![endif]-->
        <script type="text/javascript" src="/js/jquery.js"></script>
        
        <script type="text/javascript" src="/js/bootstrap.js"></script>

    </head>
    <body>
    <?php echo $this->getPartial('mainMenu', 'Primary', array('location'=>'Resources'));?>
     <h1>Resources</h1>
     <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>TYPE</th>
                <th>LOCATION</th>
                <th>OPTIONS</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->resources as $resource):?>
            <tr>                
                <td><?=$resource['type'];?></td>
                <td><?=$resource['location'];?></td>
                <td>OPTIONS</td>
            </tr>
            <?php endforeach;?>  
        </tbody>
     </table>    
    </body>
</html>