<!DOCTYPE >
<html lang="En">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Michael A. Dennis<michaeladennis@comcast.net>">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap-theme.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
            <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
            <!--[if lt IE 9]>
            <script src="/js/html5shiv.js"></script>
            <![endif]-->
        <script type="text/javascript" src="/js/jquery.js"></script>
        
        <script type="text/javascript" src="/js/bootstrap.js"></script>
        <script type="text/javascript" src="/js/aux/roles.js"></script>
        <script type="text/javascript">
            var authRoles = <?=json_encode($this->roles);?>
        </script>
    </head>
    <body>
    <?php echo $this->getPartial('mainMenu', 'Primary', array('location'=>'Roles'));?>
    <div class="container">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>ROLE</th>
                    <th><button onclick="$('#modal-container-addRole').modal('show');" class="btn btn-xs btn-success" id="modal-addRole" role="button">Add Role</button></th>
                </tr>
            </thead>            
            <tbody>
                <?php foreach($this->roles as $role):?>
                <tr>
                    <td>
                        <?=$role['id'];?>
                    </td>
                    <td>
                        <?=$role['role'];?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <button class="btn btn-xs btn-info" title="View Subordinate Role" onclick="viewRoleSubordinate('<?=$role['id'];?>', '<?=$role['role'];?>');"><em class="glyphicon glyphicon-list-alt" style="padding: 3px 3px;"></em></button>
                            <button class="btn btn-xs btn-success" title="Add Subordinate Role" onclick="addRole('<?=$role['id'];?>', 0 );"><em class="glyphicon glyphicon-plus" style="padding: 3px 3px;"></em></button>
                            <button class="btn btn-xs btn-danger" title="Remove Role & Subordinate Roles" onclick="removeRole('<?=$role['id'];?>', '<?=$role['role'];?>');"><em class="glyphicon glyphicon-trash" style="padding: 3px 3px;"></em></button>
                        </div>
                    </td>
                </tr>
                <?php endforeach;?>
            </tbody>            
        </table>
    </div>
    <div class="modal fade" id="modal-container-addRole" role="dialog" aria-labelledby="addRole" aria-hidden="true">
        <form class="form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                         
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            <em class="glyphicon glyphicon-remove"></em>
                        </button>
                        <h4 class="modal-title" id="addRole">
                            Add New Parent Role
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12" style="padding-right:0px;">
                                <div class="col-md-4" style="padding-left:0px;padding-right:0px;">
                                    <label for="role">New Role :</label>
                                </div>
                                <div class="col-md-8" style="padding-left:0px;">
                                       <input type="text" name="role" class="form-control"/>                                        
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                         
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            Close
                        </button> 
                        <button type="button" class="btn btn-primary" onclick="addParentRole();">
                            Save changes
                        </button>
                    </div>
                </div>					
            </div>
        </form> 
    </div>

    <div class="modal fade" id="modal-container-removeRole" role="dialog" aria-labelledby="removeRole" aria-hidden="true">
        <form class="form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                         
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            <em class="glyphicon glyphicon-remove"></em>'
                        </button>
                        <h4 class="modal-title" id="removeRole">
                            Remove Role
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h1><strong>Warnging!</strong> Role Removal</h1>
                                <p>By confirming to delete this role you will also delete all roles associated with it.</p>                                
                            </div>

                        </div>
                    </div>
                    <div class="modal-footer">
                         
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            Close
                        </button> 
                        <button type="button" class="btn btn-primary" onclick="removeRoleRole();">
                            Save changes
                        </button>
                    </div>
                </div>					
            </div>
        </form> 
    </div>
    </body>			 
</html>