<!DOCTYPE >
<html lang="En">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Michael A. Dennis<michaeladennis@comcast.net>">
        <link href="/css/jquery-ui.css" rel="stylesheet">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap-theme.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
            <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
            <!--[if lt IE 9]>
            <script src="/js/html5shiv.js"></script>
            <![endif]-->
        <script type="text/javascript" src="/js/jquery.js"></script>        
        <script type="text/javascript" src="/js/jquery-ui.js"></script>
        <script type="text/javascript" src="/js/bootstrap.js"></script>
        <script type="text/javascript">
            var authUsers = <?=json_encode($this->users);?>;
            var userFilterType = 'enabled';
            
        </script>
        <script type="text/javascript" src="/js/aux/users.js"></script>
    </head>
    <body>
    <?php echo $this->getPartial('mainMenu', 'Primary', array('location'=>'Users'));?>
        <div class="container">
            <table class="table table-bordered table-condensed" id="authUsers">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>FIRST NAME</th>
                        <th>LAST NAME</th>
                        <th>USERNAME</th>
                        <th>ROLE</th>
                        <th>ACTIVE</th>
                        <th>                            
                            <button onclick="$('#modal-container-addUser').modal('show');" class="btn btn-xs btn-success" id="modal-addUser" role="button" title="Add User"><em class="glyphicon glyphicon-plus" style="padding: 3px 3px;"></em> User</button>
                            <?php if($this->users[0]['active']):?>
                            <button onclick="viewDisabled();" id="modal-viewDisabledUsers" class="btn btn-xs btn-warning" role="button" title="View Disabled"><em class="glyphicon glyphicon-eye-close" style="padding: 3px 3px;"></em>  Disabled</button>
                            <?php else:?>
                            <button onclick="viewEnabled();" id="modal-viewEnabledUsers" class="btn btn-xs btn-default" role="button" title="View Enabled"><em class="glyphicon glyphicon-eye-open" style="padding: 3px 3px;"></em>  Enabled</button>
                            <?php endif;?>
                        </th>
                    </tr>
                </thead>            
                <tbody>
                    <?php foreach($this->users as $user):?>
                    <tr>
                        <td>
                            <?=$user['id'];?>
                        </td>
                        <td><?=$user['first_name'];?></td>
                        <td><?=$user['last_name'];?></td>
                        <td><?=$user['username'];?></td>
                        <td>
                            <?=$user['role'];?>
                        </td>
                        <td>
                            <?=$user['active'] ? 'Enabled':'Disabled';?>
                        </td>
                        <td>
                            <div class="btn-group">
                                <button class="btn btn-xs btn-info" title="User Profile" onclick="viewUserProfile('<?=$user['id'];?>');"><em class="glyphicon glyphicon-user" style="padding: 3px 3px;"></em></button>
                                <button class="btn btn-xs btn-info" title="User Phone Numbers" onclick="viewUserPhoneList('<?=$user['id'];?>');"><em class="glyphicon glyphicon-earphone" style="padding: 3px 3px;"></em></button>
                                <button class="btn btn-xs btn-info" title="User Addresses" onclick="viewUserAddressList('<?=$user['id'];?>');"><em class="glyphicon glyphicon-envelope" style="padding: 3px 3px;"></em></button>
                                <?php if($user['active']):?>
                                <button class="btn btn-xs btn-warning" title="Disable User" onclick="disableUser('<?=$user['id'];?>');">
                                                            <em class="glyphicon glyphicon-eye-close" style="padding: 3px 3px;"></em>
                                                     </button>
                                <?php else:?>                     
                                                     <button class="btn btn-xs btn-success" title="Enable User" onclick="enableUser('<?=$user['id'];?>');">
                                                     <em class="glyphicon glyphicon-eye-open" style="padding: 3px 3px;"></em></button>
                                <?php endif;?>
                                <button class="btn btn-xs btn-danger" title="Delete User" onclick="deleteUser('<?=$user['id'];?>');"><em class="glyphicon glyphicon-trash" style="padding: 3px 3px;"></em></button>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach;?>
                </tbody>            
            </table>
        </div>
        <div class="modal fade" id="modal-container-addUser" role="dialog" aria-labelledby="addUser" aria-hidden="true">
            <form class="form" name="addAuthUserForm">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                             
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                ×
                            </button>
                            <h4 class="modal-title" id="addUser">
                                Add Auth User 
                            </h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="form-group col-md-6">
                                        <label for="first_name">
                                            First Name
                                        </label>
                                        <input class="form-control input-sm" id="first_name" name="first_name" type="text" autocomplete="off"/> 
                                    <p class="help-block">
                                        <sub>Enter Your First Name.</sub>
                                    </p>
                                </div>
                                <div class="form-group col-md-6">
                                        <label for="last_name">
                                            Last Name
                                        </label>
                                        <input class="form-control input-sm" id="last_name" name="last_name" type="text" autocomplete="off"/>
                                    <p class="help-block">
                                        <sub>Enter Your Last Name</sub>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="phone">
                                        Phone
                                    </label>
                                    <input class="form-control input-sm" id="phone" name="phone" type="text" autocomplete="off"/>
                                    <p class="help-block">
                                        <sub>Enter Your Phone Number.</sub>
                                    </p>
                                </div>
                                <div class="form-group col-md-6 text-center" style="margin-top:18px;padding-left:0px;padding-right:0px">
                                    <label>
                                        Cell
                                    </label>
                                    <input type="radio" name="phone_type" id="cell-phone" value="cell" autocomplete="off" >
                                    <label>
                                        Landline
                                    </label>
                                    <input type="radio" name="phone_type" id="landline-phone" value="landline" autocomplete="off" >
                                    <p class="help-block">
                                        <sub>Is this a Cell or Landline?</sub>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-5">
                                    <label for="phone">
                                        Username
                                    </label>
                                    <input class="form-control input-sm" id="username" name="username" type="text" autocomplete="off" />
                                    <p class="help-block">
                                        <sub>Enter Your username.</sub>
                                    </p>
                                </div>
                                <div class="form-group col-md-7">
                                    <label for="phone">
                                        E-Mail
                                    </label>
                                    <input class="form-control input-sm" id="email" name="email" type="email" autocomplete="off"/>
                                    <p class="help-block">
                                        <sub>Enter Your E-Mail Address.</sub>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-9">
                                        <label for="address">
                                            Address
                                        </label>
                                        <input class="form-control input-sm" id="address" name="address" type="text" />
                                    <p class="help-block">
                                        <sub>Enter Your Street Address.</sub>
                                    </p>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="address_2">
                                        Apt/Ste/Lot#
                                    </label>
                                    <input class="form-control input-sm" id="address_2" name="address_2" type="text" />
                                    <p class="help-block">
                                        <sub>Enter Your Apt/Ste/Lot#.</sub>
                                    </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-5">
                                        <label for="city">
                                            City
                                        </label>
                                        <input class="form-control input-sm" id="city" name="city" type="text" />
                                    <p class="help-block">
                                        <sub>Enter Your City</sub>
                                    </p>
                                </div>
                                <div class="form-group col-md-4">
                                        <label for="state">
                                            State
                                        </label>
                                        <input class="form-control input-sm" id="state" name="state" type="text" />
                                    <p class="help-block">
                                        <sub>Select Your State/Province.</sub>
                                    </p>
                                </div>
                                <div class="form-group col-md-3">
                                        <label for="postal_code">
                                            Postal Code
                                        </label>
                                        <input class="form-control input-sm" id="postal_code" name="postal_code" type="text" />
                                    <p class="help-block">
                                        <sub>Enter A Postal Code.</sub>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                Close
                            </button>
                            <button type="button" class="btn btn-default" onclick="resetAddUser();">
                                Reset
                            </button> 
                            <button type="button" class="btn btn-primary" onclick="addUser();" >
                                Save Changes
                            </button>
                        </div>
                    </div>					
                </div>
            </form> 
        </div>
    </body>
</html>