<!DOCTYPE >
<html lang="En">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Michael A. Dennis<michaeladennis@comcast.net>">
        <link href="/css/bootstrap-theme.css" rel="stylesheet">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
            <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
            <!--[if lt IE 9]>
            <script src="/js/html5shiv.js"></script>
            <![endif]-->
        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/scripts.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php echo $this->getPartial('top-banner', 'Primary');?>
        <?php echo $this->getPartial('top-panels', 'Primary');?>
        <?php echo $this->getPartial('scoop', 'Primary');?>
    </body>
</html>



<\?php var_dump($this->test);?><br/>
<\?php echo $this->getPartial('test', 'Primary', array('mild'=>'else', 'test' => $this->test ));?><br/>
<\?php var_dump($this->getRequest()->getParam('var1'));?><br/>
<\?php var_dump($this->getRequest()->getParam('var2'));?><br/>
