        <div class="container-fluid">
            <div class="container">
                <br/>
                <nav class="navbar navbar-default" role="navigation">
                    <div class="navbar-header">
                         
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                             <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                        </button> <a class="navbar-brand" href="#">Kiss MVC</a>
                    </div>
                    
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li <?=($this->location == 'Home') ? 'class="active"':'';?>>
                                <a href="\">Home</a>
                            </li>
                            <?php echo $this->getPartial('authMenu', 'Auth');?>
                            <?php echo $this->getPartial('Menus\developersPanel', 'Auth');?>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">                            
                            <li>
                                <a href="\<?=!$this->isAuthenticated() ? 'Log-In': 'Log-Out';?>"><?=!$this->isAuthenticated() ? 'LogIn': 'LogOut';?></a>
                            </li>
                        </ul>
                    </div>				
                </nav>
                <div class="alert-wrapper"></div>
            </div>
        </div>