<section>
    <div class="container-fluid">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Simple, Small Yet Powerfull</h3>
                </div>
                <div class="panel-body">
                    <p>Simple Routing, Simple Directory Layout, and a powerful design make up this small but powerful framework.</p>
                    <p>Creating a website is as easy as replacing one file with your page, or make it as complex as you need it using partial pages.</p>
                    <p>Start with the basics and build from there.</p>
                </div>
                <div class="panel-footer">
                    <h5>Simple and Small by design.</h5>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Modular Design</h3>
                </div>
                <div class="panel-body">
                    <p>Only the most basic freatures are required for the Onyx Framework to work.</p>
                    <p>The config file comes with standard routes for a home page, and an error page.</p>
                    <p>Routing was kept simple, utilizing pretty url techniques. Extending the standard routing is kept simple. <a href="#">See more</a>.</p>                            
                </div>
                <div class="panel-footer">
                    <h5>Expandable from the start.</h5>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Ask For Help</h3>
                </div>
                <div class="panel-body">
                    
                    <p> I intend this to be open source, so make changes copies, updates or what ever you want.</p>
                    <p> Great thing about todays internet we can always ask for help. Have something you wanna share, fork the repo and share it.</p>
                    <p> Need my Help? I won't always be available but I'd be glad to help, just <a href="#">contact me</a> and I'll see what I can do for you.</p>                            
                </div>
                <div class="panel-footer">
                    <h5><a href="#">Open Source License</a>.</h5>
                </div>
            </div>
        </div>
    </div>
</section>